/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface SwapOneStepInterface extends utils.Interface {
  functions: {
    "CBDC()": FunctionFragment;
    "executeSwap(address,address,address,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "CBDC" | "executeSwap"): FunctionFragment;

  encodeFunctionData(functionFragment: "CBDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeSwap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "CBDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeSwap",
    data: BytesLike
  ): Result;

  events: {
    "SwapExecuted(uint256,uint256,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SwapExecuted"): EventFragment;
}

export interface SwapExecutedEventObject {
  senderNumber: BigNumber;
  receiverNumber: BigNumber;
  sender: string;
  receiver: string;
  amount: BigNumber;
}
export type SwapExecutedEvent = TypedEvent<
  [BigNumber, BigNumber, string, string, BigNumber],
  SwapExecutedEventObject
>;

export type SwapExecutedEventFilter = TypedEventFilter<SwapExecutedEvent>;

export interface SwapOneStep extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SwapOneStepInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CBDC(overrides?: CallOverrides): Promise<[string]>;

    executeSwap(
      tokenSender: PromiseOrValue<string>,
      tokenReceiver: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  CBDC(overrides?: CallOverrides): Promise<string>;

  executeSwap(
    tokenSender: PromiseOrValue<string>,
    tokenReceiver: PromiseOrValue<string>,
    receiver: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    CBDC(overrides?: CallOverrides): Promise<string>;

    executeSwap(
      tokenSender: PromiseOrValue<string>,
      tokenReceiver: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SwapExecuted(uint256,uint256,address,address,uint256)"(
      senderNumber?: null,
      receiverNumber?: null,
      sender?: null,
      receiver?: null,
      amount?: null
    ): SwapExecutedEventFilter;
    SwapExecuted(
      senderNumber?: null,
      receiverNumber?: null,
      sender?: null,
      receiver?: null,
      amount?: null
    ): SwapExecutedEventFilter;
  };

  estimateGas: {
    CBDC(overrides?: CallOverrides): Promise<BigNumber>;

    executeSwap(
      tokenSender: PromiseOrValue<string>,
      tokenReceiver: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CBDC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeSwap(
      tokenSender: PromiseOrValue<string>,
      tokenReceiver: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
